---
# Hard-disk-ul virtual pentru date
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pvc
  namespace: licenta-iot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Aplicația în sine (Containerul)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: licenta-iot
spec:
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - name: timescaledb
        image: timescale/timescaledb:latest-pg14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef: 
              name: licenta-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: licenta-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom: 
            secretKeyRef: 
              name: licenta-secrets
              key: POSTGRES_DB
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: timescaledb-pvc

---
# Router-ul intern (IP-ul fix)
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: licenta-iot
spec:
  selector:
    app: timescaledb
  ports:
  - port: 5432
    targetPort: 5432
