---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: licenta-iot
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672  # Portul pentru mesaje
        - containerPort: 15672 # Portul pentru interfața web
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom: 
            secretKeyRef: 
              name: licenta-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom: 
            secretKeyRef: 
              name: licenta-secrets
              key: RABBITMQ_DEFAULT_PASS

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: licenta-iot
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
