apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: licenta-iot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: licenta-worker:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: licenta-secrets
                  key: DB_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: licenta-secrets
                  key: RABBITMQ_URL
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "800m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: worker-metrics
  namespace: licenta-iot
spec:
  selector:
    app: worker
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-hpa
  namespace: licenta-iot
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
